### ISSUE TITLE
Line endings not accounted for in logging

### ISSUE THREAD

**Issue by mrunalp** [kubernetes-incubator/cri-o#429]
Reported by @runcom during testing (it was a TODO in conmon ;) )

envar-demo.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  restartPolicy: Never
  containers:
  - name: envar-demo-container
    image: gcr.io/google_containers/busybox:1.24
    command: ["sh", "-c", "env"]
    env:
    - name: FOO
      value: "foo-value"
    - name: BAR
      value: "bar-value"
    - name: FOOBAR
      value: "$(FOO);;$(BAR)"
```
Only one line is printed from output of env. 
```
$ kubectl create -f envar-demo.yaml
$ pod "envar-demo" created
$ kubectl logs envar-demo
KUBERNETES_PORT=tcp://10.0.0.1:443
```
